Calorie_Dict = {
    'Hamburger': 250,
    'Cheeseburger':	300,
    'Double Cheeseburger':	440,
    'McDouble':	390,
    'Quarter Pounder with Cheese': 510,
    'Double Quarter Pounder with Cheese': 740,
    'Big Mac':	540,
    "Big N' Tasty":	460,
    "Big N' Tasty with Cheese":	510,
    'Angus Bacon & Cheese':	790,
    'Angus Deluxe':	750,
    "Angus Mushroom & Swiss": 770,
    'Filet-O-Fish':	380,
    'McChicken': 360,
    'McRib': 500,
    'Premium Grilled Chicken Classic Sandwhich':	360,
    'Premium Crispy Chicken Classic Sandwhich':	510,
    'Premium Grilled Chicken Club Sandwhich':	460,
    'Premium Crispy Chicken Club Sandwhich':	620,
    'Premium Grilled Chicken Ranch BLT Sandwhich':	380,
    'Premium Crispy Chicken Ranch BLT Sandwhich':	540,
    'Southern Style Crispy Chicken Sandwhich':	400,
    'Ranch Snack Wrap(Crispy)':	340,
    'Ranch Snack Wrap(Grilled)':	270,
    'Honey Mustard Snack Wrap(Crispy)':	330,
    'Honey Mustard Snack Wrap(Grilled)':	260,
    'Chipotle BBQ Snack Wrap(Crispy)':	330,
    'Chiptole BBQ Snack Wrap(Grilled)':	260,
    'Angus Bacon & Cheese Snack Wrap':	390,
    'Angus Chipotle BBQ Bacon':	800,
    'Angus Chipotle BBQ Bacon Snack Wrap':	400,
    'Angus Deluxe Snack Wrap':	410,
    'Angus Mushroom & Swiss Snack Wrap':	430,
    'Mac Snack Wrap':	330,
    'Small French Fries':	230,
    'Medium French Fries': 	380,
    'Large French Fries':	500,
    'Ketchup Packet':	15,
    'Chicken McNuggets(4 Piece)':	190,
    'Chicken McNuggets(6 Piece)':	280,
    'Chicken McNuggets(10 Piece)':	470,
    'Barbeque Sauce':	50,
    'Honey':	50,
    'Hot Mustard Sauce':	60,
    "Sweet 'N Sour Sauce":	50,
    'Chicken Selects Premium Breast Strips(3 pc)':	400,
    'Chicken Selects Premium Breast Strips(5 pc)':	660,
    'Spicy Buffalo Sauce':	60,
    'Creamy Ranch Sauce':	170,
    'Tangy Honey Mustard Sauce':	60,
    'Southwestern Chiptole Barbeque Sauce':	60,
    'Premium Southwest Salad with Grilled Chicken':	320,
    'Premium Southwest Salad with Crispy Chicken':	430,
    'Premium Southwest Salad(without chicken)':	140,
    'Premium Bacon Ranch Salad with Grilled Chicken':	260,
    'Premium Bacon Ranch Salad with Crispy Chicken':	370,
    'Premium Bacon Ranch Salad(without chicken)':	140,
    'Premium Caesar Salad with Grilled Chicken':	220,
    'Premium Caesar Salad with Crispy Chicken':	330,
    'Premium Caesar Salad(without chicken)':	90,
    'Side Salad':	20,
    'Butter Garlic Croutons':	60,
    'Snack Size Fruit & Walnut Salad':	210,
    "Newman's Own Creamy Southwest Dressing":	100,
    "Newman's Own Creamy Caesar Dressing":	190,
    "Newman's Own Low Fat Balsamic Vinaigrette":	40,
    "Newman's Own Low Fat Family Recipe Italian Dressing":	60,
    "Newman's Own Ranch Dressing":	170,
    'Egg McMuffin':	300,
    'Sausage McMuffin':	370,
    'Sausage McMuffin with Egg':	450,
    'English Muffin':	160,
    'Bacon, Egg & Cheese Biscuit(Regular Size Biscuit)':	420,
    'Bacon, Egg & Cheese Biscuit(Large Size Biscuit)':	480,
    'Sausage Biscuit with Egg(Regular Size Biscuit)':	510,
    'Sausage Biscuit with Egg(Large Size Biscuit)':	570,
    'Sausage Biscuit(Regular Size Biscuit)':	430,
    'Sausage Biscuit(Large Size Biscuit)':	480,
    'Southern Style Chicken Biscuit(Regular Size Biscuit)':	410,
    'Southern Style Chicken Biscuit(Large Size Biscuit)':	470,
    'Steak, Egg & Cheese Bagel':	660,
    'Bacon, Egg & Cheese McGriddles':	420,
    'Sausage, Egg & Cheese McGriddles':	560,
    'Sausage McGriddles':	420,
    'Big Breakfast(Regular Size Biscuit)':	740,
    'Big Breakfast(Large Size Biscuit)':	800,
    'Big Breakfast with Hotcakes(Regular Size Biscuit)':	1090,
    'Big Breakfast with Hotcakes(Large Size Biscuit)':	1150,
    'Sausage Burrito':	300,
    'McSkillet Burrito with Sausage':	610,
    'Hotcakes':	350,
    'Hotcakes and Sausage':	520,
    'Hotcake Syrup':	180,
    'Whipped Margarine(1 pat)':	40,
    'Hash Brown':	150,
    'Grape Jam':	35,
    'Strawberry Preserves':	35,
    'Bacon, Egg & Cheese Bagel':	560,
    'Fruit & Maple Oatmeal':	290,
    'Fruit & Maple Oatmeal without Brown Sugar':	260,
    'Hamburger Happy Meal':	475,
    '4 Piece Chicken McNuggets':	395,
    '6 Piece Chicken McNuggets Happy Meal':	475,
    "Fruit 'n Yogurt Parfait (7 oz)":	160,
    'Low Fat Caramel Dip':	70,
    'Vanilla Reduced Fat Ice Cream Cone':	150,
    'Kiddie Cone':	45,
    'Strawberry Sundae':	280,
    'Hot Caramel Sundae':	340,
    'Hot Fudge Sundae':	330,
    'Peanuts (for Sundaes)':	45,
    "McFlurry with M&M'S Candies (12 fl oz cup)":	710,
    'McFlurry with OREO Cookies (12 fl oz cup)':	580,
    'Baked Hot Apple Pie':	250,
    'Cinnamon Melts':	460,
    'McDonaldland Cookies':	260,
    'Chocolate Chip Cookie':	160,
    'Oatmeal Raisin Cookie':	150,
    'Sugar Cookie':	160,
    'Apple Dippers with Low Fat Caramel Dip':	100,
    'Chocolate McCafe Shake (12 fl oz cup)':	580,
    'Chocolate McCafe Shake (16 fl oz cup)':	720,
    'Chocolate McCafe Shake(22 fl oz cup)':	880,
    'Chocolate Triple Thick Shake (12 fl oz cup)':	440,
    'Chocolate Triple Thick Shake (16 fl oz cup)':	580,
    'Chocolate Triple Thick Shake (21 fl oz cup)':	770,
    'Chocolate Triple Thick Shake (32 fl oz cup)':	1160,
    "Snack Size McFlurry with M&M'S Candies":	430,
    'Snack Size McFlurry with OREO Cookies':	340,
    'Strawberry McCafe Shake (12 fl oz cup)':	570,
    'Strawberry McCafe Shake (16 fl oz cup)':	710,
    'Strawberry McCafe Shake (22 fl oz cup)':	860,
    'Strawberry Triple Thick Shake (12 fl oz cup)':	420,
    'Strawberry Triple Thick Shake (16 fl oz cup)':	560,
    'Strawberry Triple Thick Shake (21 fl oz cup)':	740,
    'Strawberry Triple Thick Shake (32 fl oz cup)':	1110,
    'Vanilla McCafe Shake (12 fl oz cup)':	540,
    'Vanilla McCafe Shake (16 fl oz cup)':	680,
    'Vanilla McCafe Shake (22 fl oz cup)':	830,
    'Vanilla McCafe Shake (32 fl oz cup)':	1110,
    'Vanilla Triple Thick Shake (12 fl oz cup)':	420,
    'Vanilla Triple Thick Shake (16 fl oz cup)':	550,
    'Vanilla Triple Thick Shake (21 fl oz cup)':	740,
    '1 Percent Low Fat Milk Jug':	100,
    '1 Percent Low Fat Chocolate Milk Jug':	170,
    'Minute Maid 100% Apple Juice Box':	100,
    'Dasani Water':	0,
    'Minute Maid Orange Juice (Small)':	150,
    'Minute Maid Orange Juice (Medium)':	190,
    'Minute Maid Orange Juice (Large)':	280,
    'Coca-Cola Classic (Child)':	110,
    'Coca-Cola Classic (Small)':	150,
    'Coca-Cola Classic (Medium)':	210,
    'Coca-Cola Classic (Large)':	310,
    'Diet Coke (Child)':	0,
    'Diet Coke (Small)':	0,
    'Diet Coke (Medium)':	0,
    'Diet Coke (Large)':	0,
    'Sprite (Child)':	110,
    'Sprite (Small)':	150,
    'Sprite (Medium)':	210,
    'Sprite (Large)':	310,
    'Hi-C Orange Lavaburst (Child)':	120,
    'Hi-C Orange Lavaburst (Small)':	160,
    'Hi-C Orange Lavaburst (Medium)':	240,
    'Hi-C Orange Lavaburst (Large)':	350,
    'Powerade Mountain Blast (Child)':	70,
    'Powerade Mountain Blast (Small)':	100,
    'Powerade Mountain Blast (Medium)':	150,
    'Powerade Mountain Blast (Large)':	220,
    'Iced Tea (Child)':	0,
    'Iced Tea (Small)':	0,
    'Iced Tea (Medium)':	0,
    'Iced Tea (Large)':	0,
    'Coffee (Small)':	0,
    'Coffee (Large)':	0,
    'Coffee Cream':	20,
    'Sugar Packet':	15,
    'Iced Coffee-Caramel (Small)':	130,
    'Iced Coffee-Caramel (Medium)':	190,
    'Iced Coffee-Caramel (Large)':	270,
    'Iced Coffee-Hazelnut (Small)':	130,
    'Iced Coffee-Hazelnut (Medium)':	190,
    'Iced Coffee-Hazelnut (Large)':	270,
    'Iced Coffee-Regular (Small)':	140,
    'Iced Coffee-Regular (Medium)':	200,
    'Iced Coffee-Regular (Large)':	280,
    'Iced Coffee-Vanilla (Small)':	130,
    'Iced Coffee-Vanilla (Medium)':	190,
    'Iced Coffee-Vanilla (Large)':	270,
    'Iced Coffee with Sugar Free Vanilla Syrup (Small)':	60,
    'Iced Coffee with Sugar Free Vanilla Syrup (Medium)':	90,
    'Iced Coffee with Sugar Free Vanilla Syrup (Large)':	120,
    'Sweet Tea (Child)':	110,
    'Sweet Tea (Small)':	150,
    'Sweet Tea (Medium)':	180,
    'Sweet Tea (Large)':	280,
    'Nonfat Cappuccino (Small)':	60,
    'Nonfat Cappuccino (Medium)':	80,
    'Nonfat Cappuccino (Large)':	90,
    'Nonfat Latte (Small)':	90,
    'Nonfat Latte (Medium)':	110,
    'Nonfat Latte (Large)':	120,
    'Nonfat Caramel Cuppuccino (Small)':	150,
    'Nonfat Caramel Cuppuccino (Medium)':	190,
    'Nonfat Caramel Cuppuccino (Large)':	230,
    'Nonfat Caramel Latte (Small)':	170,
    'Nonfat Caramel Latte (Medium)':	220,
    'Nonfat Caramel Latte (Large)':	260,
    'Nonfat Hazelnut Cappuccino (Small)':	150,
    'Nonfat Hazelnut Cappuccino (Medium)':	190,
    'Nonfat Hazelnut Cappuccino (Large)':	230,
    'Nonfat Hazelnut Latte (Small)':	180,
    'Nonfat Hazelnut Latte (Medium)':	220,
    'Nonfat Hazelnut Latte (Large)':	260,
    'Nonfat Vanilla Cappuccino (Small)':	150,
    'Nonfat Vanilla Cappuccino (Medium)':	190,
    'Nonfat Vanilla Cappuccino (Large)':	230,
    'Nonfat Vanilla Latte (Small)':	180,
    'Nonfat Vanilla Latte (Medium)':	220,
    'Nonfat Vanilla Latte (Large)':	260,
    'Nonfat Cappuccino with Sugar Free Vanilla Syrup (Small)':	50,
    'Nonfat Cappuccino with Sugar Free Vanilla Syrup (Medium)': 70,
    'Nonfat Cappuccino with Sugar Free Vanilla Syrup (Large)':	80,
    'Nonfat Latte with Sugar Free Vanilla Syrup (Small)':	80,
    'Nonfat Latte with Sugar Free Vanilla Syrup (Medium)':	90,
    'Nonfat Latte with Sugar Free Vanilla Syrup (Large)':	110,
    'Mocha with Nonfat Milk (Small)':	240,
    'Mocha with Nonfat Milk (Medium)':	280,
    'Mocha with Nonfat Milk (Large)':	330,
    'Hot Chocolate with Nonfat Milk (Small)':	250,
    'Hot Chocolate with Nonfat Milk (Medium)':	310,
    'Hot Chocolate with Nonfat Milk (Large)':	390,
    'Iced Nonfat Latte (Small)':	50,
    'Iced Nonfat Latte (Medium)':	60,
    'Iced Nonfat Latte (Large)':	70,
    'Iced Nonfat Caramel Latte (Small)':	140,
    'Iced Nonfat Caramel Latte (Medium)':	150,
    'Iced Nonfat Caramel Latte (Large)':	190,
    'Iced Nonfat Hazelnut Latte (Small)':	140,
    'Iced Nonfat Hazelnut Latte (Medium)':	150,
    'Iced Nonfat Hazelnut Latte (Large)':	190,
    'Iced Nonfat Vanilla Latte (Small)':	140,
    'Iced Nonfat Vanilla Latte (Medium)':	150,
    'Iced Nonfat Vanilla Latte (Large)':	190,
    'Iced Nonfat Latte with Sugar Free Vanilla Syrup (Small)':	40,
    'Iced Nonfat Latte with Sugar Free Vanilla Syrup (Medium)': 50,
    'Iced Nonfat Latte with Sugar Free Vanilla Syrup (Large)':	60,
    'Iced Mocha with Nonfat Milk (Medium)':	270,
    'Iced Nonfat Caramel Mocha (Small)':	200,
    'Iced Nonfat Caramel Mocha (Medium)':	240,
    'Iced Nonfat Caramel Mocha (Large)':	300,
    'Nonfat Caramel Mocha (Small)':	200,
    'Nonfat Caramel Mocha (Medium)':	240,
    'Nonfat Caramel Mocha (Large)':	280,
    'Cappuccino (Small)':	120,
    'Cappuccino (Medium)':	140,
    'Cappuccino (Large)':	180,
    'Latte (Small)':	150,
    'Latte (Medium)':	180,
    'Latte (Large)':	210,
    'Caramel Cappuccino (Small)':	200,
    'Caramel Cappuccino (Medium)':	240,
    'Caramel Cappuccino (Large)':	290,
    'Caramel Latte (Small)':	230,
    'Caramel Latte (Medium)':	280,
    'Caramel Latte (Large)':	330,
    'Hazelnut Cappuccino (Small)':	200,
    'Hazelnut Cappuccino (Medium)':	240,
    'Hazelnut Cappuccino (Large)':	290,
    'Hazelnut Latte (Small)':	230,
    'Hazelnut Latte (Medium)':	280,
    'Hazelnut Latte (Large)':	330,
    'Vanilla Cappuccino (Small)':	200,
    'Vanilla Cappuccino (Medium)':	240,
    'Vanilla Cappuccino (Large)':	290,
    'Vanila Latte (Small)':	230,
    'Vanila Latte (Medium)':	280,
    'Vanila Latte (Large)':	330,
    'Cappuccino with Sugar Free Vanilla Syrup (Small)':	100,
    'Cappuccino with Sugar Free Vanilla Syrup (Medium)':	120,
    'Cappuccino with Sugar Free Vanilla Syrup (Large)':	150,
    'Latte with Sugar Free Vanilla Syrup (Small)':	130,
    'Latte with Sugar Free Vanilla Syrup (Medium)': 160,
    'Latte with Sugar Free Vanilla Syrup (Large)':	180,
    'Mocha (Small)':	280,
    'Mocha (Medium)':	330,
    'Mocha (Large)':	400,
    'Hot Chocolate (Small)':	300,
    'Hot Chocolate (Medium)':	380,
    'Hot Chocolate (Large)':	460,
    'Iced Latte (Small)':	80,
    'Iced Latte (Medium)':	100,
    'Iced Latte (Large)':	140,
    'Iced Caramel Latte (Small)':	160,
    'Iced Caramel Latte (Medium)':	180,
    'Iced Caramel Latte (Large)':	230,
    'Iced Hazelnut Latte (Small)':	160,
    'Iced Hazelnut Latte (Medium)': 180,
    'Iced Hazelnut Latte (Large)':	230,
    'Iced Vanilla Latte (Small)':	160,
    'Iced Vanilla Latte (Medium)':	190,
    'Iced Vanilla Latte (Large)':	230,
    'Iced Latte with Sugar Free Vanilla Syrup (Small)': 60,
    'Iced Latte with Sugar Free Vanilla Syrup (Medium)': 90,
    'Iced Latte with Sugar Free Vanilla Syrup (Large)': 110,
    'Iced Mocha (Medium)':	310,
    'Caramel Mocha (Small)':	250,
    'Caramel Mocha (Medium)':	290,
    'Caramel Mocha (Large)':	360,
    'Iced Caramel Mocha (Small)':	240,
    'Iced Caramel Mocha (Medium)':	300,
    'Iced Caramel Mocha (Large)':	380,
    'Frappe Caramel (Small)':	450,
    'Frappe Caramel (Medium)':	550,
    'Frappe Caramel (Large)':	680,
    'Frappe Mocha (Small)':	450,
    'Frappe Mocha (Medium)':	560,
    'Frappe Mocha (Large)':	680,
    'Strawberry Banana Smoothie (Small)':	210,
    'Strawberry Banana Smoothie (Medium)':	260,
    'Strawberry Banana Smoothie (Large)':	330,
    'Wild Berry Smoothie (Small)':	210,
    'Wild Berry Smoothie (Medium)': 260,
    'Wild Berry Smoothie (Large)':	320,
}